project:
  type: website
  output-dir: docs

website:
  title: "Shohruh Miryusupov"
  site-url: "https://www.miryusupov.com"

format:
  html:
    theme: none
    css: styles.css
    html-math-method: katex
    toc: false
    include-before-body: _nav.html
    link-external-newwindow: false
    anchor-sections: false
    smooth-scroll: false
