<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-05-06">
<meta name="description" content="A note on conformal validity, score geometry, and efficient prediction sets.">

<title>Conformal Scores and the Geometry of Efficiency – Shohruh Miryusupov</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-html-640605f58ae58ee79329c070719e555b.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body>

<nav class="site-nav">
  <a class="nav-name" href="../../../">Shohruh Miryusupov</a>
  <div class="nav-links">
    <a href="../../../blog/">Writings</a>
    <a href="../../../about.html">About</a>
    <a href="https://github.com/smiryusupov">GitHub</a>
  </div>
</nav>

<header id="title-block-header">
<h1 class="title">Conformal Scores and the Geometry of Efficiency</h1>

<p class="date">2026-05-06</p>
</header>


<style>
/* Wider result tables for this post. Normal site tables stay unchanged. */
.wide-table {
  max-width: min(100vw - 2rem, 980px);
  margin-left: 50%;
  transform: translateX(-50%);
  overflow-x: auto;
}

.wide-table table,
.wide-table .table {
  width: 100% !important;
  max-width: none !important;
  margin-left: 0 !important;
  margin-right: 0 !important;
}

.wide-table th,
.wide-table td {
  white-space: nowrap;
}

@media (max-width: 700px) {
  .wide-table {
    max-width: calc(100vw - 1rem);
  }
}
</style>
<p><em>Status: research note; not peer reviewed. The conformal validity claims are standard; the experiments study how score choice changes efficiency and local behavior.</em></p>
<h2 id="preface">Preface</h2>
<p>Conformal prediction has a clean promise. If the calibration and test examples are exchangeable, then a split conformal prediction set has finite-sample marginal coverage. The model used to build the score can be wrong. The likelihood can be misspecified. The geometry can be only approximate.</p>
<p>That is the part I do not want to disturb. The question in this note is different:</p>
<blockquote>
<p>If conformal validity is model-free, where can model geometry matter?</p>
</blockquote>
<p>My answer is:</p>
<blockquote>
<p>Geometry enters through the nonconformity score. It does not prove coverage. It changes efficiency.</p>
</blockquote>
<p>So the slogan is</p>
<p><span class="math display">
\boxed{\text{exchangeability gives validity; score geometry affects efficiency.}}
</span></p>
<p>This note is a small experiment around that slogan. The goal is not to introduce a new conformal method, but to separate two things that are easy to mix together: the validity mechanism and the shape induced by the score. Conformal calibration gives the first. The score gives the second.</p>
<h2 id="part-i-validity-comes-from-exchangeability">Part I: Validity comes from exchangeability</h2>
<p>Let</p>
<p><span class="math display">
Z_i=(X_i,Y_i), \qquad i=1,\ldots,n+1,
</span></p>
<p>be exchangeable observations, and let</p>
<p><span class="math display">
S:\mathcal X\times\mathcal Y\to\mathbb R
</span></p>
<p>be any measurable nonconformity score. On a calibration set, define</p>
<p><span class="math display">
R_i=S(X_i,Y_i).
</span></p>
<p>For target miscoverage <span class="math inline">\alpha</span>, use the conformal quantile</p>
<p><span class="math display">
\widehat q
=
R_{\left(\lceil (n_{\mathrm{cal}}+1)(1-\alpha)\rceil\right)}.
</span></p>
<p>The split conformal set is</p>
<p><span class="math display">
C_\alpha(x)=\{y:S(x,y)\le \widehat q\}.
</span></p>
<p>Then</p>
<p><span class="math display">
\mathbb P\{Y_{n+1}\in C_\alpha(X_{n+1})\}\ge 1-\alpha.
</span></p>
<p>The important word is <em>any</em>. The score can come from a random forest, a kernel method, a neural network, a quantile model, or a density model. If the calibration and test scores are exchangeable, the marginal guarantee remains.</p>
<p>This is why I do not view information geometry as a new validity proof for conformal prediction. The validity proof is already there. The role of geometry is narrower: a geometric score may rank candidate labels better. Better ranking can mean shorter intervals, smaller sets, or better conditional behavior. But it is not what makes the method valid.</p>
<h2 id="part-ii-the-score-defines-the-geometry">Part II: The score defines the geometry</h2>
<p>The simplest regression score is</p>
<p><span class="math display">
S_{\mathrm{abs}}(x,y)=|y-\widehat\mu(x)|.
</span></p>
<p>It creates a global residual interval,</p>
<p><span class="math display">
C_\alpha(x)
=
[\widehat\mu(x)-\widehat q,\widehat\mu(x)+\widehat q].
</span></p>
<p>This is a reasonable geometry when the conditional noise is roughly symmetric and has the same scale everywhere. When the noise scale changes with <span class="math inline">x</span>, a global residual threshold tends to be too wide in easy regions and too narrow in hard regions. Marginal coverage can still be right, because the errors average out.</p>
<p>A local-scale score changes the ruler:</p>
<p><span class="math display">
S_{\mathrm{loc}}(x,y)
=
\frac{|y-\widehat\mu(x)|}{\widehat\sigma(x)}.
</span></p>
<p>The resulting interval is</p>
<p><span class="math display">
C_\alpha(x)
=
[
\widehat\mu(x)-\widehat q\widehat\sigma(x),
\widehat\mu(x)+\widehat q\widehat\sigma(x)
].
</span></p>
<p>This is a one-dimensional Mahalanobis idea. The local ruler is</p>
<p><span class="math display">
g(x)\approx \frac{1}{\widehat\sigma^2(x)}.
</span></p>
<p>In a Gaussian conditional model,</p>
<p><span class="math display">
Y\mid X=x\sim N(\mu(x),\sigma^2(x)),
</span></p>
<p>the negative log-likelihood contains</p>
<p><span class="math display">
\frac{(y-\mu(x))^2}{2\sigma^2(x)}.
</span></p>
<p>So local normalization measures residual size in the local uncertainty units of the model. The conformal step does not care whether the Gaussian story is true. It only uses the resulting ranks. But the efficiency can care a lot.</p>
<p>There are other geometries. Conformalized quantile regression uses lower and upper quantile models,</p>
<p><span class="math display">
\widehat q_\ell(x),\qquad \widehat q_u(x),
</span></p>
<p>with score</p>
<p><span class="math display">
S_{\mathrm{CQR}}(x,y)
=
\max\{\widehat q_\ell(x)-y,\;y-\widehat q_u(x)\}.
</span></p>
<p>The resulting interval is no longer forced to be symmetric around a mean. For multimodal data, even quantile intervals can be the wrong shape: if two separated labels are plausible and the middle is implausible, a single interval wastes volume. A density score,</p>
<p><span class="math display">
S_{\mathrm{dens}}(x,y)=-\log \widehat p(y\mid x),
</span></p>
<p>instead gives the set</p>
<p><span class="math display">
C_\alpha(x)=\{y:\widehat p(y\mid x)\ge e^{-\widehat q}\},
</span></p>
<p>which can be disconnected. That is the right geometry for multimodal conditional laws.</p>
<h2 id="part-iii-geometry-has-to-be-estimated">Part III: Geometry has to be estimated</h2>
<p>A local metric can help only if it is estimated stably. If <span class="math inline">\widehat\sigma(x)</span> is too small on some calibration points, then</p>
<p><span class="math display">
\frac{|y-\widehat\mu(x)|}{\widehat\sigma(x)}
</span></p>
<p>can become huge. The conformal quantile then becomes huge, and the final intervals can explode.</p>
<p>To make this failure mode visible, I use stabilized local scales,</p>
<p><span class="math display">
\widetilde\sigma(x)
=
\operatorname{clip}(\widehat\sigma(x),s_{\min},s_{\max})+\lambda,
</span></p>
<p>and a local/global blend,</p>
<p><span class="math display">
\widetilde\sigma_\gamma(x)
=
(1-\gamma)\widetilde\sigma_{\mathrm{local}}(x)
+
\gamma\widetilde\sigma_{\mathrm{global}}.
</span></p>
<p>Here <span class="math inline">\gamma=0</span> is fully local geometry, while <span class="math inline">\gamma=1</span> is mostly global residual geometry. The practical question is not whether local geometry is elegant. It is how much local geometry we can trust.</p>
<h2 id="part-iv-the-experiment">Part IV: The experiment</h2>
<p>I use synthetic regression data with mean</p>
<p><span class="math display">
\mu(x)=\sin(2\pi x_1)+\frac12 x_1.
</span></p>
<p>The settings are deliberately simple.</p>
<div class="wide-table">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Setting</th>
<th>Data-generating idea</th>
<th>What it tests</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Homoskedastic</td>
<td><span class="math inline">Y=\mu(X)+0.25\varepsilon</span>, <span class="math inline">\varepsilon\sim N(0,1)</span></td>
<td>no local scale structure</td>
</tr>
<tr class="even">
<td>Heteroskedastic</td>
<td><span class="math inline">Y=\mu(X)+\sigma(X)\varepsilon</span>, <span class="math inline">\sigma(x)=0.10+0.80|x_1|</span></td>
<td>local scale geometry</td>
</tr>
<tr class="odd">
<td>Heavy-tailed</td>
<td><span class="math inline">\varepsilon\sim t_3/\sqrt3</span></td>
<td>robustness</td>
</tr>
<tr class="even">
<td>Skewed</td>
<td><span class="math inline">\varepsilon\sim \mathrm{Exponential}(1)-1</span></td>
<td>asymmetric errors</td>
</tr>
<tr class="odd">
<td>Multimodal</td>
<td><span class="math inline">Y=\mu(X)+0.8B+\sigma(X)\varepsilon</span>, <span class="math inline">B\in\{-1,+1\}</span></td>
<td>disconnected conditional structure</td>
</tr>
</tbody>
</table>
</div>
<p>The experiment is ordinary split conformal: split the data into train, calibration, and test sets; fit a model on the training set; build one or more scores; compute the conformal quantile on calibration scores; and evaluate coverage and set length on the test set.</p>
<p>The score changes. The calibration logic does not.</p>
<p>The code lives in <code>ig_conformal.py</code>. I ran the full benchmark separately and report the saved summaries below. The benchmark uses four model families: random forests, kernel ridge regression, MLPs, and GBRT-based conformalized quantile regression.</p>
<h2 id="part-v-what-happened">Part V: What happened</h2>
<p>The results match the small claim. Coverage stays near <span class="math inline">90\%</span> for most methods. That is the conformal part. The average length changes a lot. That is the score-geometry part.</p>
<h3 id="heteroskedastic-data">Heteroskedastic data</h3>
<p>This is the clearest positive case for local geometry.</p>
<div class="wide-table">
<table class="caption-top">
<colgroup>
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>model</th>
<th style="text-align: right;">baseline len.</th>
<th>geometric score</th>
<th style="text-align: right;">geometric len.</th>
<th style="text-align: right;">reduction</th>
<th style="text-align: right;">baseline cond. err.</th>
<th style="text-align: right;">geometric cond. err.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GBRT-CQR</td>
<td style="text-align: right;">1.904</td>
<td>conformalized quantile regression</td>
<td style="text-align: right;">1.697</td>
<td style="text-align: right;">10.9%</td>
<td style="text-align: right;">0.088</td>
<td style="text-align: right;">0.026</td>
</tr>
<tr class="even">
<td>KRR</td>
<td style="text-align: right;">2.579</td>
<td>blended normalized residual, <span class="math inline">\gamma=0.75</span></td>
<td style="text-align: right;">2.683</td>
<td style="text-align: right;">-4.0%</td>
<td style="text-align: right;">0.080</td>
<td style="text-align: right;">0.069</td>
</tr>
<tr class="odd">
<td>MLP</td>
<td style="text-align: right;">1.988</td>
<td>stabilized normalized residual</td>
<td style="text-align: right;">1.784</td>
<td style="text-align: right;">10.3%</td>
<td style="text-align: right;">0.096</td>
<td style="text-align: right;">0.038</td>
</tr>
<tr class="even">
<td>RF</td>
<td style="text-align: right;">1.950</td>
<td>blended normalized residual, <span class="math inline">\gamma=0.25</span></td>
<td style="text-align: right;">1.676</td>
<td style="text-align: right;">14.1%</td>
<td style="text-align: right;">0.086</td>
<td style="text-align: right;">0.047</td>
</tr>
</tbody>
</table>
</div>
<p>For random forests, the average length drops from about <span class="math inline">1.95</span> to <span class="math inline">1.68</span>. For MLPs, it drops from about <span class="math inline">1.99</span> to <span class="math inline">1.78</span>. For GBRT-CQR, it drops from about <span class="math inline">1.90</span> to <span class="math inline">1.70</span>. The conditional coverage diagnostics also improve.</p>
<p>Kernel ridge regression is the warning. In this run, even the best blended geometry is slightly longer than the global residual baseline. In more aggressive local-normalization variants, the intervals can become enormous because the estimated scale is unstable. That is not a conformal failure. Coverage is still protected. It is a score failure.</p>
<p>The practical lesson is:</p>
<blockquote>
<p>use only as much geometry as you can estimate stably.</p>
</blockquote>
<h3 id="homoskedastic-heavy-tailed-and-skewed-data">Homoskedastic, heavy-tailed, and skewed data</h3>
<p>The homoskedastic case is a useful sanity check. The simple residual score is hard to beat; for random forests, the absolute residual interval has average length about <span class="math inline">0.856</span>, and the oracle local normalization gives essentially the same number. Local geometry has nothing useful to learn.</p>
<p>The heavy-tailed and skewed cases are mixed but informative. Blended local-scale scores give modest gains for RF and MLP in the heavy-tailed setting and often improve conditional balance. In the skewed setting, RF and MLP blended scores work well, while CQR improves conditional balance but is not uniformly shorter in this particular run. More flexible geometry is not automatically better. It helps only when the fitted score ranks labels well.</p>
<h2 id="part-vi-the-multimodal-case">Part VI: The multimodal case</h2>
<p>The multimodal setting is the cleanest example. Interval methods have the wrong shape: they must cover the space between modes even when the middle is not very plausible.</p>
<p>The conditional density score uses</p>
<p><span class="math display">
S(x,y)=-\log \widehat p(y\mid x).
</span></p>
<p>I fit a simple two-mode conditional density model,</p>
<p><span class="math display">
\widehat p(y\mid x)
=
\widehat\pi(x)\mathcal N(y;\widehat\mu_+(x),\widehat\sigma_+^2)
+
(1-\widehat\pi(x))\mathcal N(y;\widehat\mu_-(x),\widehat\sigma_-^2).
</span></p>
<p>This is not meant to be a state-of-the-art density estimator. It is just expressive enough to test the geometry. The density-level-set conformal method gives average length about <span class="math inline">1.82</span> with coverage about <span class="math inline">0.904</span>.</p>
<div class="wide-table">
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>baseline family</th>
<th style="text-align: right;">interval baseline len.</th>
<th style="text-align: right;">density-set len.</th>
<th style="text-align: right;">reduction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GBRT-CQR</td>
<td style="text-align: right;">2.345</td>
<td style="text-align: right;">1.820</td>
<td style="text-align: right;">22.4%</td>
</tr>
<tr class="even">
<td>KRR</td>
<td style="text-align: right;">3.803</td>
<td style="text-align: right;">1.820</td>
<td style="text-align: right;">52.1%</td>
</tr>
<tr class="odd">
<td>MLP</td>
<td style="text-align: right;">2.691</td>
<td style="text-align: right;">1.820</td>
<td style="text-align: right;">32.4%</td>
</tr>
<tr class="even">
<td>RF</td>
<td style="text-align: right;">2.457</td>
<td style="text-align: right;">1.820</td>
<td style="text-align: right;">25.9%</td>
</tr>
</tbody>
</table>
</div>
<p>This is the main idea in its most visible form:</p>
<blockquote>
<p>once the score geometry matches the conditional law, conformal sets become much more efficient.</p>
</blockquote>
<h2 id="part-vii-diagnostics-should-match-the-geometry">Part VII: Diagnostics should match the geometry</h2>
<p>At first, the density method looked less locally balanced when I binned by <span class="math inline">\sigma(x)</span>. The mean conditional error was about <span class="math inline">0.0757</span>. But <span class="math inline">\sigma(x)</span> is not the right diagnostic for a mixture score. The score models mode structure.</p>
<p>So I also bin by mixture-specific quantities: the estimated upper-mode probability <span class="math inline">\widehat\pi(x)</span>, its entropy <span class="math inline">H(\widehat\pi(x))</span>, the mode margin <span class="math inline">|\widehat\pi(x)-0.5|</span>, and the mode separation <span class="math inline">|\widehat\mu_+(x)-\widehat\mu_-(x)|</span>.</p>
<div class="wide-table">
<table class="caption-top">
<thead>
<tr class="header">
<th>diagnostic</th>
<th style="text-align: right;">mean conditional error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\sigma(x)</span> bins</td>
<td style="text-align: right;">0.0757</td>
</tr>
<tr class="even">
<td><span class="math inline">\widehat\pi(x)</span> bins</td>
<td style="text-align: right;">0.0232</td>
</tr>
<tr class="odd">
<td>mode entropy bins</td>
<td style="text-align: right;">0.0240</td>
</tr>
<tr class="even">
<td>mode margin bins</td>
<td style="text-align: right;">0.0240</td>
</tr>
<tr class="odd">
<td>mode separation bins</td>
<td style="text-align: right;">0.0248</td>
</tr>
</tbody>
</table>
</div>
<p>The earlier diagnostic was partly asking the wrong question. If the score models local scale, bin by local scale. If the score models mixture uncertainty, bin by mixture uncertainty.</p>
<h2 id="takeaway">Takeaway</h2>
<p>This experiment is not a theorem about optimal conformal prediction. The claim is smaller:</p>
<blockquote>
<p>conformal calibration gives marginal validity, while the score determines the geometry of the set.</p>
</blockquote>
<p>That leads to the practical question:</p>
<blockquote>
<p>does the score geometry match the conditional law of <span class="math inline">Y\mid X</span>?</p>
</blockquote>
<p>When the answer is yes, conformal sets can be much smaller. When the answer is no, coverage can remain valid while efficiency degrades.</p>
<p>A simple taxonomy is:</p>
<p><span class="math display">
\boxed{\text{flat noise} \Rightarrow \text{residual score}}
</span></p>
<p><span class="math display">
\boxed{\text{heteroskedasticity} \Rightarrow \text{local scale score}}
</span></p>
<p><span class="math display">
\boxed{\text{varying quantiles} \Rightarrow \text{CQR}}
</span></p>
<p><span class="math display">
\boxed{\text{multimodality} \Rightarrow \text{density-level-set score}.}
</span></p>
<p>The conformal layer is the safety net. It turns model-dependent scores into marginally valid prediction sets. But it does not make all scores equally good.</p>
<h2 id="technical-appendix">Technical appendix</h2>
<h3 id="why-monotone-score-transforms-did-not-matter">Why monotone score transforms did not matter</h3>
<p>I initially tried Student-<span class="math inline">t</span> and Huber versions of normalized residual scores. In scalar symmetric regression, these are mostly rank-equivalent to normalized absolute residuals. For example,</p>
<p><span class="math display">
\log\left(1+\frac{r^2}{\nu}\right)
</span></p>
<p>is monotone in <span class="math inline">|r|</span>, and the Huber loss is also monotone in <span class="math inline">|r|</span>. Since conformal prediction is rank-based, these transformations do not change the prediction set if they use the same scale. They may be useful diagnostics, but they do not create a new scalar interval geometry.</p>
<h3 id="what-density-set-length-means">What density-set length means</h3>
<p>For density-level-set conformal prediction in one-dimensional regression, I approximate</p>
<p><span class="math display">
|C_\alpha(x)|
</span></p>
<p>on a grid. The accepted grid points are those satisfying</p>
<p><span class="math display">
-\log \widehat p(y\mid x)\le \widehat q.
</span></p>
<p>If the density has two separated modes, the accepted grid points can form two disconnected intervals. The reported length is the total grid length of the accepted region.</p>
<h3 id="a-classification-analogue">A classification analogue</h3>
<p>The same idea has a classification analogue. For a neural classifier, ordinary conformal scores use softmax probabilities,</p>
<p><span class="math display">
S(x,y)=1-\widehat p_\theta(y\mid x),
</span></p>
<p>or cumulative-probability rankings. A more geometric score could use the penultimate-layer representation <span class="math inline">\phi_\theta(x)</span>. For class <span class="math inline">y</span>, fit a class center <span class="math inline">m_y</span> and covariance <span class="math inline">\Sigma_y</span>, then use</p>
<p><span class="math display">
S(x,y)
=
(\phi_\theta(x)-m_y)^\top
\Sigma_y^{-1}
(\phi_\theta(x)-m_y).
</span></p>
<p>This is the classification analogue of local metric scores in regression. The network supplies the geometry. Conformal calibration supplies the validity.</p>
<h3 id="why-this-is-not-a-validity-theorem">Why this is not a validity theorem</h3>
<p>All validity statements here are ordinary split conformal validity statements. The new part is empirical and conceptual: different score geometries induce different set shapes and efficiencies.</p>
<p>A formal theorem would need to control excess set size, for example</p>
<p><span class="math display">
\mathbb E|C_\alpha(X)|-\mathbb E|C_\alpha^*(X)|,
</span></p>
<p>in terms of score-ranking error, density-estimation error, or metric-estimation error. That is not proved here.</p>
<h3 id="reproducing-the-benchmark">Reproducing the benchmark</h3>
<p>The full benchmark can be regenerated from <code>ig_conformal.py</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>raw, summary <span class="op">=</span> ig.run_grid(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    settings<span class="op">=</span>[</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">"homoskedastic"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">"heteroskedastic"</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">"heavy_tail"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"skewed"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">"multimodal"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    model_families<span class="op">=</span>[<span class="st">"rf"</span>, <span class="st">"krr"</span>, <span class="st">"mlp"</span>, <span class="st">"cqr_gbrt"</span>],</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    n<span class="op">=</span><span class="dv">6000</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    d<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.1</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    seeds<span class="op">=</span>[<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>],</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    save_csv<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    output_prefix<span class="op">=</span><span class="st">"ig_conformal_results"</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>compact <span class="op">=</span> ig.summarize_geometry_effect(summary)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>compact.to_csv(<span class="st">"ig_conformal_geometry_effect.csv"</span>, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>multimodal_diag <span class="op">=</span> ig.summarize_multimodal_density_diagnostics(summary)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>multimodal_diag.to_csv(</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ig_conformal_multimodal_density_diagnostics.csv"</span>,</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    index<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<h2 id="references">References</h2>
<p>Vladimir Vovk, Alexander Gammerman, and Glenn Shafer. <em>Algorithmic Learning in a Random World</em>. Springer, 2005.</p>
<p>Glenn Shafer and Vladimir Vovk. “A Tutorial on Conformal Prediction.” <em>Journal of Machine Learning Research</em> 9, 371–421, 2008.</p>
<p>Jing Lei, Max G’Sell, Alessandro Rinaldo, Ryan J. Tibshirani, and Larry Wasserman. “Distribution-Free Predictive Inference for Regression.” <em>Journal of the American Statistical Association</em> 113(523), 1094–1111, 2018.</p>
<p>Yaniv Romano, Evan Patterson, and Emmanuel Candès. “Conformalized Quantile Regression.” <em>NeurIPS</em>, 2019.</p>
<p>Anastasios Angelopoulos and Stephen Bates. “A Gentle Introduction to Conformal Prediction and Distribution-Free Uncertainty Quantification.” arXiv:2107.07511, 2021.</p>
<p>Rob Hyndman. “Computing and Graphing Highest Density Regions.” <em>The American Statistician</em> 50(2), 120–126, 1996.</p>
<p>Rafael Izbicki, Gilson Shimizu, and Rafael Stern. “Flexible Distribution-Free Conditional Predictive Bands using Density Estimators.” <em>AISTATS</em>, 2020.</p>
<p>Shun-ichi Amari. <em>Information Geometry and Its Applications</em>. Springer, 2016.</p>
<h2 id="suggested-citation">Suggested citation</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="va">@misc</span>{<span class="ot">miryusupov2026conformalgeometry</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>       = {Miryusupov, Shohruh},</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>        = {Conformal Scores and the Geometry of Efficiency},</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>         = {2026},</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">howpublished</span> = {Research note},</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">url</span>          = {https://www.miryusupov.com/blog/posts/conformal-scores-geometry-efficiency/}</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>


<footer id="site-footer" class="site-footer">
  <span class="site-disclaimer">
    Personal academic site. Independent work, using personal equipment and public sources; does not represent my employer.
  </span>
</footer>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const footer = document.getElementById("site-footer");
    if (footer) {
      document.body.appendChild(footer);
    }
  });
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/www\.miryusupov\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




</body></html>