<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-05-28">
<meta name="description" content="A note on why MMD and other distribution discrepancies are not, by themselves, classifier-risk statements.">

<title>Discrepancy is not risk – Shohruh Miryusupov</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-html-640605f58ae58ee79329c070719e555b.min.css" rel="stylesheet" append-hash="true" data-mode="light">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body>

<nav class="site-nav">
  <a class="nav-name" href="../../../">Shohruh Miryusupov</a>
  <div class="nav-links">
    <a href="../../../blog/">Writings</a>
    <a href="../../../projects/">Projects</a>
    <a href="../../../about.html">About</a>
    <a href="https://github.com/smiryusupov">GitHub</a>
  </div>
</nav>

<header id="title-block-header">
<h1 class="title">Discrepancy is not risk</h1>

<p class="date">2026-05-28</p>
</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#three-objects-three-questions" id="toc-three-objects-three-questions">Three objects, three questions</a></li>
  <li><a href="#why-t-and-d-are-useful-reference-points" id="toc-why-t-and-d-are-useful-reference-points">Why T and D are useful reference points</a></li>
  <li><a href="#diagnostic-1-the-same-linear-mmd-can-mean-different-errors" id="toc-diagnostic-1-the-same-linear-mmd-can-mean-different-errors">Diagnostic 1: the same linear MMD can mean different errors</a></li>
  <li><a href="#diagnostic-2-rbf-mmd-can-shrink-while-error-stays-fixed" id="toc-diagnostic-2-rbf-mmd-can-shrink-while-error-stays-fixed">Diagnostic 2: RBF-MMD can shrink while error stays fixed</a></li>
  <li><a href="#diagnostic-3-mmd-can-see-a-difference-that-mean-rules-cannot-use" id="toc-diagnostic-3-mmd-can-see-a-difference-that-mean-rules-cannot-use">Diagnostic 3: MMD can see a difference that mean rules cannot use</a></li>
  <li><a href="#diagnostic-4-the-wrong-geometry-can-make-a-good-signal-look-useless" id="toc-diagnostic-4-the-wrong-geometry-can-make-a-good-signal-look-useless">Diagnostic 4: the wrong geometry can make a good signal look useless</a></li>
  <li><a href="#diagnostic-5-a-shortcut-swap-in-a-vision-representation" id="toc-diagnostic-5-a-shortcut-swap-in-a-vision-representation">Diagnostic 5: a shortcut swap in a vision representation</a></li>
  <li><a href="#technical-addendum-gaussian-looking-risk-formulas-can-still-be-wrong" id="toc-technical-addendum-gaussian-looking-risk-formulas-can-still-be-wrong">Technical addendum: Gaussian-looking risk formulas can still be wrong</a></li>
  <li><a href="#summary-of-the-diagnostics" id="toc-summary-of-the-diagnostics">Summary of the diagnostics</a></li>
  <li><a href="#what-this-says-about-ml-practice" id="toc-what-this-says-about-ml-practice">What this says about ML practice</a></li>
  <li><a href="#takeaway" id="toc-takeaway">Takeaway</a></li>
  <li><a href="#references" id="toc-references">References</a></li>
  <li><a href="#suggested-citation" id="toc-suggested-citation">Suggested citation</a></li>
  </ul>
</nav>
<p>A distribution discrepancy answers one question. A classifier risk answers another.</p>
<p>This distinction is easy to lose because the same words keep appearing: distance, separation, alignment, mismatch. MMD, Wasserstein distance, Euclidean distance, Mahalanobis distance, and learned embedding distances all sound as if they measure whether two classes or two domains are easy to tell apart.</p>
<p>Sometimes they do. Often they do not.</p>
<p>A two-sample discrepancy compresses a comparison into one number,</p>
<p><span class="math display">
D(P,Q).
</span></p>
<p>If this number is large, the distributions are far apart in the chosen geometry. If it is small, they are close in that geometry. That is the right answer when the question is a two-sample question.</p>
<p>Classification asks for something more specific. A new observation <span class="math inline">z</span> comes from one of two populations, say <span class="math inline">\pi_1</span> or <span class="math inline">\pi_2</span>, and a particular rule <span class="math inline">\widehat g</span> will be used. The relevant quantity is not just whether <span class="math inline">\pi_1\ne\pi_2</span>. It is the error of that rule:</p>
<p><span class="math display">
P\{\widehat g(z)=2\mid z\in\pi_1\}.
</span></p>
<p>That is a different object. A discrepancy compares distributions. A risk evaluates a decision rule.</p>
<p>The examples below are deliberately small. They are not arguments against MMD, Wasserstein distance, or other discrepancies, and they are not arguments in favor of T-rules or D-rules. They isolate a single failure mode: reading a geometry-dependent distribution comparison as if it were the risk of the classifier actually being deployed.</p>
<h2 id="three-objects-three-questions">Three objects, three questions</h2>
<p>Let</p>
<p><span class="math display">
X_1,\ldots,X_{n_1}\sim \pi_1,
\qquad
Y_1,\ldots,Y_{n_2}\sim \pi_2,
</span></p>
<p>with means <span class="math inline">\mu_1,\mu_2</span> and, in the classical setup, common covariance <span class="math inline">\Sigma</span>. A new observation <span class="math inline">z</span> must be assigned to one of the two populations.</p>
<p>The T-rule compares corrected Euclidean distances to the two sample centers:</p>
<p><span class="math display">
\alpha_1\|z-\bar X\|^2
\quad\text{and}\quad
\alpha_2\|z-\bar Y\|^2,
\qquad
\alpha_i=\frac{n_i}{n_i+1}.
</span></p>
<p>For a true <span class="math inline">\pi_1</span> observation, its false assignment probability is</p>
<p><span class="math display">
P_T(2\mid 1)
=
P\left\{
\alpha_1\|z-\bar X\|^2-
\alpha_2\|z-\bar Y\|^2&gt;0
\mid z\in\pi_1
\right\}.
</span></p>
<p>The D-rule uses covariance-scaled geometry instead. In the population version, the relevant mean separation is</p>
<p><span class="math display">
\Delta^2=(\mu_1-\mu_2)^\top\Sigma^{-1}(\mu_1-\mu_2).
</span></p>
<p>MMD asks a different question. For a reproducing-kernel Hilbert space <span class="math inline">\mathcal H</span> with kernel <span class="math inline">k</span>,</p>
<p><span class="math display">
\operatorname{MMD}(P,Q)
=
\sup_{\|f\|_{\mathcal H}\le 1}
\left|E_P f(X)-E_Q f(Y)\right|.
</span></p>
<p>So the table is not a list of interchangeable distances. It is a list of different questions.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>object</th>
<th>question</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>T-rule</td>
<td>What is the error of a Euclidean center rule?</td>
</tr>
<tr class="even">
<td>D-rule</td>
<td>What is the error of a covariance-scaled center rule?</td>
</tr>
<tr class="odd">
<td>MMD</td>
<td>Are two distributions different in the chosen RKHS geometry?</td>
</tr>
</tbody>
</table>
<p>The rest of the note is about what goes wrong when one answer is read as another.</p>
<h2 id="why-t-and-d-are-useful-reference-points">Why T and D are useful reference points</h2>
<p>T-type and D-type rules are useful here because they make a basic high-dimensional tension visible.</p>
<p>In low dimension, the natural instinct is</p>
<p><span class="math display">
\text{estimate covariance}
\rightarrow
\text{invert it}
\rightarrow
\text{use Mahalanobis geometry}.
</span></p>
<p>That is the D philosophy. It can be very good when the covariance estimate is reliable, because it uses scale and correlation structure.</p>
<p>In high dimension, the covariance matrix is itself a noisy object. When <span class="math inline">p/n</span> is not small, its eigenvalues no longer behave like classical fixed-<span class="math inline">p</span> quantities. If <span class="math inline">p&gt;n</span>, the sample covariance is singular. Even when <span class="math inline">p&lt;n</span>, inversion can amplify spectral noise.</p>
<p>The T philosophy avoids covariance inversion. It uses Euclidean or trace information instead of the full inverse covariance. This sacrifices affine invariance, but it can be stable when the D philosophy is fragile.</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>regime</th>
<th>D-type / Mahalanobis logic</th>
<th>T-type / trace logic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">p</span> small, <span class="math inline">n</span> large</td>
<td>often excellent</td>
<td>may ignore useful covariance structure</td>
</tr>
<tr class="even">
<td><span class="math inline">p/n</span> non-negligible</td>
<td>affected by random-matrix noise</td>
<td>often more stable</td>
</tr>
<tr class="odd">
<td><span class="math inline">p&gt;n</span></td>
<td>needs regularization or becomes undefined</td>
<td>still directly defined</td>
</tr>
<tr class="even">
<td>signal in low-variance correlated direction</td>
<td>can be much better</td>
<td>can miss the right geometry</td>
</tr>
<tr class="odd">
<td>covariance estimate unreliable</td>
<td>can overfit badly</td>
<td>may be safer</td>
</tr>
</tbody>
</table>
<p>This is the statistical version of a practical ML question:</p>
<blockquote>
<p>Should I trust the learned geometry, or use a cruder but stabler one?</p>
</blockquote>
<p>A deep embedding may have dimension 768, 2048, or larger, while the labeled sample per class is modest. A full covariance-based rule can be fragile. A Euclidean prototype rule can be biased but stable. A kernel discrepancy such as MMD can be meaningful as a distribution test while still saying little about the finite-sample risk of the classifier that will actually be deployed.</p>
<p>The operative question is</p>
<p><span class="math display">
\text{What is the distribution of the decision statistic, and what error does it imply?}
</span></p>
<p>More plainly: what error does the actual rule make?</p>
<p>In the first few diagnostics I use population, known-parameter analogues of the T/D rules. That removes estimation noise, so the distinction between discrepancy and decision risk is not hidden by finite-sample terms.</p>
<h2 id="diagnostic-1-the-same-linear-mmd-can-mean-different-errors">Diagnostic 1: the same linear MMD can mean different errors</h2>
<p>Start with the one-dimensional Gaussian pair</p>
<p><span class="math display">
\pi_1=N(0,\sigma^2),
\qquad
\pi_2=N(1,\sigma^2).
</span></p>
<p>With the linear kernel</p>
<p><span class="math display">
k(x,y)=xy,
</span></p>
<p>MMD reduces to squared mean difference:</p>
<p><span class="math display">
\operatorname{MMD}^2(\pi_1,\pi_2)=|0-1|^2=1.
</span></p>
<p>So the discrepancy is identical for every <span class="math inline">\sigma</span>.</p>
<p>The classification error is not. With known means and common variance, the T-rule and D-rule have the same one-dimensional boundary,</p>
<p><span class="math display">
z=\frac12.
</span></p>
<p>Therefore</p>
<p><span class="math display">
P\{\widehat g(z)=2\mid z\in\pi_1\}
=
P\{Z&gt;1/2\},
\qquad
Z\sim N(0,\sigma^2),
</span></p>
<p>and hence</p>
<p><span class="math display">
P\{\widehat g(z)=2\mid z\in\pi_1\}
=1-\Phi\left(\frac{1}{2\sigma}\right).
</span></p>
<p>A one-unit mean shift is enormous when <span class="math inline">\sigma=0.1</span>. It is almost invisible when <span class="math inline">\sigma=100</span>.</p>
<div id="tbl-linear-mmd-sigma" class="cell quarto-float quarto-figure quarto-figure-center" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-linear-mmd-sigma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-linear-mmd-sigma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">\sigma</span></th>
<th>linear MMD<span class="math inline">^2</span></th>
<th>known T/D error <span class="math inline">P(2\mid 1)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.1</td>
<td>1.000</td>
<td>2.87e-07</td>
</tr>
<tr class="even">
<td>1.0</td>
<td>1.000</td>
<td>0.30853754</td>
</tr>
<tr class="odd">
<td>10.0</td>
<td>1.000</td>
<td>0.48006119</td>
</tr>
<tr class="even">
<td>100.0</td>
<td>1.000</td>
<td>0.49800530</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The MMD value did not change. The classification meaning did. The discrepancy is correct in its chosen geometry; it is just not a risk calculation.</p>
<h2 id="diagnostic-2-rbf-mmd-can-shrink-while-error-stays-fixed">Diagnostic 2: RBF-MMD can shrink while error stays fixed</h2>
<p>The previous example used the linear kernel because the algebra is transparent. A high-dimensional version appears with the Gaussian RBF kernel.</p>
<p>Let</p>
<p><span class="math display">
\pi_1=N_p(0,I_p),
\qquad
\pi_2=N_p(2e_1,I_p),
</span></p>
<p>where only the first coordinate separates the classes.</p>
<p>The Bayes rule, known-mean T-rule, and known-covariance D-rule all have the same error:</p>
<p><span class="math display">
P(2\mid 1)=\Phi(-1)\approx 0.1587.
</span></p>
<p>This error does not depend on <span class="math inline">p</span>. The signal remains two standard deviations apart in the first coordinate.</p>
<p>Now use the RBF kernel</p>
<p><span class="math display">
k(x,y)=\exp\left(-\frac{\|x-y\|^2}{2\tau^2}\right),
\qquad
\tau^2=2p.
</span></p>
<p>For equal-covariance Gaussians with mean difference <span class="math inline">2e_1</span>,</p>
<p><span class="math display">
\operatorname{MMD}^2
=
2\left(1+\frac{1}{p}\right)^{-p/2}
\left[1-\exp\left(-\frac{1}{p+1}\right)\right].
</span></p>
<p>The classification error is fixed. The RBF-MMD value decays at order <span class="math inline">1/p</span>.</p>
<div id="tbl-rbf-mmd-high-d" class="cell quarto-float quarto-figure quarto-figure-center" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-rbf-mmd-high-d-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2
</figcaption>
<div aria-describedby="tbl-rbf-mmd-high-d-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top">
<thead>
<tr class="header">
<th><span class="math inline">p</span></th>
<th>RBF-MMD<span class="math inline">^2</span>, <span class="math inline">\tau^2=2p</span></th>
<th>known-rule error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>0.3780</td>
<td>0.1587</td>
</tr>
<tr class="even">
<td>5</td>
<td>0.1946</td>
<td>0.1587</td>
</tr>
<tr class="odd">
<td>10</td>
<td>0.1079</td>
<td>0.1587</td>
</tr>
<tr class="even">
<td>20</td>
<td>0.0571</td>
<td>0.1587</td>
</tr>
<tr class="odd">
<td>50</td>
<td>0.0237</td>
<td>0.1587</td>
</tr>
<tr class="even">
<td>100</td>
<td>0.0120</td>
<td>0.1587</td>
</tr>
<tr class="odd">
<td>200</td>
<td>0.0060</td>
<td>0.1587</td>
</tr>
<tr class="even">
<td>500</td>
<td>0.0024</td>
<td>0.1587</td>
</tr>
<tr class="odd">
<td>1000</td>
<td>0.0012</td>
<td>0.1587</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Nothing mysterious is happening. The classifier uses the coordinate that carries the signal. The kernel discrepancy, with this bandwidth, spreads the comparison across the full ambient distance.</p>
<p>So a small MMD value does not imply high classification error. Nor does a large MMD value identify the error of the classifier being used. It only reports separation in the chosen kernel geometry.</p>
<p>In this example, that geometry is not aligned with the discriminative coordinate.</p>
<h2 id="diagnostic-3-mmd-can-see-a-difference-that-mean-rules-cannot-use">Diagnostic 3: MMD can see a difference that mean rules cannot use</h2>
<p>Now reverse the problem. Let</p>
<p><span class="math display">
\pi_1=N_p(0,I_p),
\qquad
\pi_2=N_p(0,\operatorname{diag}(9,1,\ldots,1)).
</span></p>
<p>The means are equal:</p>
<p><span class="math display">
\mu_1=\mu_2=0.
</span></p>
<p>A T-rule, and the usual common-covariance D-rule when used only for mean separation, has no mean direction to use. At the population level, the center comparison carries no class information, so the error is random:</p>
<p><span class="math display">
P(2\mid 1)=\frac12.
</span></p>
<p>But the distributions are not equal. The first coordinate has variance 1 under <span class="math inline">\pi_1</span> and variance 9 under <span class="math inline">\pi_2</span>. An RBF-MMD can detect this.</p>
<div id="tbl-covariance-only-difference" class="cell quarto-float quarto-figure quarto-figure-center" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-covariance-only-difference-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3
</figcaption>
<div aria-describedby="tbl-covariance-only-difference-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>method/object</th>
<th>what it sees</th>
<th>value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>T/D mean rule</td>
<td>no mean separation</td>
<td>0.5000 error</td>
</tr>
<tr class="even">
<td>RBF-MMD</td>
<td>variance difference</td>
<td>0.0299 MMD<span class="math inline">^2</span></td>
</tr>
<tr class="odd">
<td>Bayes quadratic rule</td>
<td>variance separation</td>
<td>0.1159 false <span class="math inline">2\mid 1</span> error</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A quadratic Bayes rule can exploit the variance difference. In the one-coordinate variance example, the false assignment probability under <span class="math inline">\pi_1</span> is</p>
<p><span class="math display">
P(2\mid 1)
=
P\left\{|Z|&gt;
\sqrt{\frac{2\log 3}{1-1/9}}
\right\},
\qquad
Z\sim N(0,1),
</span></p>
<p>which is approximately <span class="math inline">0.1159</span>.</p>
<p>So there are three correct answers:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>object</th>
<th>answer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MMD</td>
<td>the distributions differ</td>
</tr>
<tr class="even">
<td>T/D mean rule</td>
<td>there is no usable mean direction under this rule</td>
</tr>
<tr class="odd">
<td>Bayes quadratic rule</td>
<td>the variance difference is usable if the classifier may use it</td>
</tr>
</tbody>
</table>
<p>None of these answers is wrong. Trouble starts when one is used as a substitute for the others.</p>
<h2 id="diagnostic-4-the-wrong-geometry-can-make-a-good-signal-look-useless">Diagnostic 4: the wrong geometry can make a good signal look useless</h2>
<p>Now keep common covariance and mean separation, but change the geometry.</p>
<p>Let</p>
<p><span class="math display">
\pi_1=N_2(-\delta/2,\Sigma),
\qquad
\pi_2=N_2(\delta/2,\Sigma),
</span></p>
<p>with</p>
<p><span class="math display">
\delta=(1,1),
\qquad
\Sigma=\operatorname{diag}(0.1^2,10^2).
</span></p>
<p>There is one stable coordinate and one noisy coordinate. The Euclidean T-rule uses the direction <span class="math inline">\delta=(1,1)</span>, giving the noisy coordinate the same coefficient as the stable coordinate.</p>
<p>The population T-rule error is</p>
<p><span class="math display">
P_T(2\mid 1)
=
\Phi\left(
-\frac{\|\delta\|^2}{2\sqrt{\delta^\top\Sigma\delta}}
\right).
</span></p>
<p>The D-rule uses covariance-scaled geometry. Its error is</p>
<p><span class="math display">
P_D(2\mid 1)
=
\Phi\left(
-\frac12
\sqrt{\delta^\top\Sigma^{-1}\delta}
\right).
</span></p>
<div id="tbl-t-vs-d-geometry" class="cell quarto-float quarto-figure quarto-figure-center" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-t-vs-d-geometry-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4
</figcaption>
<div aria-describedby="tbl-t-vs-d-geometry-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>rule</th>
<th>signal scale</th>
<th>variance scale</th>
<th>error <span class="math inline">P(2\mid 1)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>T-rule / Euclidean</td>
<td><span class="math inline">\\|\delta\\|^2=2.00</span></td>
<td><span class="math inline">\delta^\top\Sigma\delta=100.01</span></td>
<td>0.46017415</td>
</tr>
<tr class="even">
<td>D-rule / Mahalanobis</td>
<td><span class="math inline">\Delta^2=100.01</span></td>
<td>covariance-scaled</td>
<td>2.86e-07</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The populations, means, and covariance have not changed. Only the decision geometry has.</p>
<p>This is the T/D lesson in miniature: classifier risk depends on the decision geometry, not only on whether the distributions differ.</p>
<h2 id="diagnostic-5-a-shortcut-swap-in-a-vision-representation">Diagnostic 5: a shortcut swap in a vision representation</h2>
<p>A computer-vision version is a shortcut-feature example.</p>
<p>Imagine a binary image classification problem. The true label is the object category, but the source training set contains a shortcut: background color, texture, lighting, camera type, or acquisition artifact. A model can classify the source domain perfectly using that shortcut.</p>
<p>Let the learned representation be one scalar,</p>
<p><span class="math display">
h(x)\in\{-1,+1\},
</span></p>
<p>where <span class="math inline">h</span> records the shortcut rather than the object. In the source domain,</p>
<p><span class="math display">
Y=+1 \Rightarrow h=+1,
\qquad
Y=-1 \Rightarrow h=-1.
</span></p>
<p>In the target domain, the shortcut relation is reversed:</p>
<p><span class="math display">
Y=+1 \Rightarrow h=-1,
\qquad
Y=-1 \Rightarrow h=+1.
</span></p>
<p>Assume the class prior is balanced in both domains:</p>
<p><span class="math display">
P(Y=+1)=P(Y=-1)=\frac12.
</span></p>
<p>Then the marginal feature distribution is identical in the two domains:</p>
<p><span class="math display">
P_S(h=+1)=P_T(h=+1)=\frac12,
\qquad
P_S(h=-1)=P_T(h=-1)=\frac12.
</span></p>
<p>Therefore the MMD between the unlabeled source and target feature distributions is exactly zero, for any kernel, because the two marginal distributions are the same.</p>
<p>But the source-trained classifier</p>
<p><span class="math display">
\widehat g(h)=\operatorname{sign}(h)
</span></p>
<p>has source error <span class="math inline">0</span> and target error <span class="math inline">1</span>.</p>
<div id="tbl-cv-shortcut-swap" class="cell quarto-float quarto-figure quarto-figure-center" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-cv-shortcut-swap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5
</figcaption>
<div aria-describedby="tbl-cv-shortcut-swap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>quantity</th>
<th>value</th>
<th>interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>source marginal <span class="math inline">P_S(h)</span></td>
<td>uniform on <span class="math inline">\{-1,+1\}</span></td>
<td>balanced shortcut feature</td>
</tr>
<tr class="even">
<td>target marginal <span class="math inline">P_T(h)</span></td>
<td>uniform on <span class="math inline">\{-1,+1\}</span></td>
<td>same unlabeled feature distribution</td>
</tr>
<tr class="odd">
<td><span class="math inline">\operatorname{MMD}^2(P_S(h),P_T(h))</span></td>
<td>0</td>
<td>perfect marginal alignment</td>
</tr>
<tr class="even">
<td>source error of <span class="math inline">\operatorname{sign}(h)</span></td>
<td>0</td>
<td>shortcut works in source</td>
</tr>
<tr class="odd">
<td>target error of <span class="math inline">\operatorname{sign}(h)</span></td>
<td>1</td>
<td>shortcut reverses in target</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The class-conditional discrepancy tells a different story. With the linear kernel on <span class="math inline">h</span>,</p>
<p><span class="math display">
\operatorname{MMD}^2
\left(P_S(h\mid Y=+1),P_T(h\mid Y=+1)\right)
=
(1-(-1))^2=4.
</span></p>
<p>So MMD is not blind here. It sees the marginal feature distribution correctly. That is precisely why it misses the shortcut reversal: the relevant object is label-conditional.</p>
<p>In computer-vision language: matching the global distribution of features, textures, backgrounds, or styles does not by itself guarantee that the object-label decision boundary is aligned. A domain discrepancy can improve while the target classifier is still using the wrong visual cue.</p>
<h2 id="technical-addendum-gaussian-looking-risk-formulas-can-still-be-wrong">Technical addendum: Gaussian-looking risk formulas can still be wrong</h2>
<p>A related but more technical warning appears after the decision rule has already been chosen. Even then, the risk formula may depend on distributional features that are invisible to a first-and-second-moment summary. This section is less about MMD and more about the danger of replacing a decision statistic by an overly Gaussian approximation.</p>
<p>Gaussian formulas are tempting because they are clean. But high-dimensional T-rule approximations for general populations can contain higher-moment terms. Third and fourth moments can enter the variance of the decision statistic.</p>
<p>For learned representations, this is not a corner case. They can be skewed, sparse, heavy-tailed, clipped, quantized, or produced by nonlinear activations.</p>
<p>Consider the simplified common-covariance model</p>
<p><span class="math display">
\pi_1: z=u,
\qquad
\pi_2: z=u+\delta,
\qquad
\Sigma=I_p,
</span></p>
<p>where the coordinates of <span class="math inline">u</span> are independent and standardized:</p>
<p><span class="math display">
E u_j=0,
\qquad
E u_j^2=1,
\qquad
E u_j^3=\theta,
\qquad
E u_j^4=\gamma.
</span></p>
<p>For equal sample sizes <span class="math inline">n_1=n_2=n</span>, write</p>
<p><span class="math display">
\alpha=\frac{n}{n+1}.
</span></p>
<p>A representative large-dimensional T-rule approximation has the form</p>
<p><span class="math display">
P_T(2\mid 1)
\approx
\Phi\left(-\frac{\alpha\|\delta\|^2}{B_p}\right),
</span></p>
<p>where, in the diagonal identity-covariance case, the variance scale has terms of the schematic form</p>
<p><span class="math display">
B_p^2
\approx
\left[\beta_0+\frac{2\alpha^2\gamma}{n^3}\right]p
+\frac{4\theta}{n^2}\mathbf 1^\top\delta
+4\alpha\|\delta\|^2.
</span></p>
<p>The exact constants depend on the asymptotic setup and normalization. The structural point is what matters here:</p>
<p><span class="math display">
\text{classification error can depend on } \gamma \text{ and } \theta.
</span></p>
<p>Two representations can have the same mean and covariance while producing different T-rule errors because their coordinate distributions have different skewness or tail behavior.</p>
<div id="tbl-higher-moments" class="cell quarto-float quarto-figure quarto-figure-center" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-higher-moments-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6
</figcaption>
<div aria-describedby="tbl-higher-moments-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top">
<thead>
<tr class="header">
<th>coordinate law</th>
<th>fourth moment <span class="math inline">\gamma</span></th>
<th>T-rule approximation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rademacher-like, light-tailed</td>
<td>1</td>
<td>0.1496</td>
</tr>
<tr class="even">
<td>Gaussian</td>
<td>3</td>
<td>0.1500</td>
</tr>
<tr class="odd">
<td>moderately heavy-tailed</td>
<td>9</td>
<td>0.1513</td>
</tr>
<tr class="even">
<td>spiky finite-moment</td>
<td>100</td>
<td>0.1683</td>
</tr>
<tr class="odd">
<td>very spiky finite-moment</td>
<td>500</td>
<td>0.2221</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The Gaussian line reports approximately <span class="math inline">0.1500</span>. With the same mean and covariance but a very spiky finite-moment representation, the approximation is closer to <span class="math inline">0.2221</span>.</p>
<p>Skewness can also enter. If <span class="math inline">\mathbf 1^\top\delta\ne0</span>, the third-moment term changes the variance of the T-rule statistic.</p>
<div id="tbl-skewness-t-rule" class="cell quarto-float quarto-figure quarto-figure-center" data-execution_count="8">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-skewness-t-rule-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7
</figcaption>
<div aria-describedby="tbl-skewness-t-rule-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top">
<thead>
<tr class="header">
<th>skewness <span class="math inline">\theta</span></th>
<th>T-rule approximation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>-4</td>
<td>0.1456</td>
</tr>
<tr class="even">
<td>-2</td>
<td>0.1485</td>
</tr>
<tr class="odd">
<td>0</td>
<td>0.1513</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.1540</td>
</tr>
<tr class="odd">
<td>4</td>
<td>0.1566</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The ML warning is small but important: whitening fixes first and second moments. It does not make a representation Gaussian. It also does not make a Gaussian error formula automatically correct.</p>
<h2 id="summary-of-the-diagnostics">Summary of the diagnostics</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>diagnostic</th>
<th>discrepancy says</th>
<th>classifier risk says</th>
<th>lesson</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>same linear MMD, different <span class="math inline">\sigma</span></td>
<td>unchanged</td>
<td>changes from near zero to near random</td>
<td>scale matters</td>
</tr>
<tr class="even">
<td>RBF-MMD in high <span class="math inline">p</span></td>
<td>shrinks</td>
<td>fixed</td>
<td>ambient geometry can dilute signal</td>
</tr>
<tr class="odd">
<td>variance-only difference</td>
<td>detects distribution difference</td>
<td>mean rule fails</td>
<td>distribution difference need not be usable by a given rule</td>
</tr>
<tr class="even">
<td>T versus D geometry</td>
<td>same populations</td>
<td>different errors</td>
<td>rule geometry matters</td>
</tr>
<tr class="odd">
<td>shortcut swap</td>
<td>marginal MMD is zero</td>
<td>target error is maximal</td>
<td>unlabeled alignment can miss label-conditional failure</td>
</tr>
<tr class="even">
<td>non-Gaussian moments</td>
<td>first two moments agree</td>
<td>approximate risk changes</td>
<td>higher moments can affect decision statistics</td>
</tr>
</tbody>
</table>
<h2 id="what-this-says-about-ml-practice">What this says about ML practice</h2>
<p>The practical failure is not MMD-specific. It is the habit of replacing downstream error by a proxy geometry.</p>
<p>A representation method may reduce MMD between domains. A contrastive objective may separate pairs. A retrieval metric may put some objects close. A Wasserstein loss may reduce transport cost. Each statement can be true while the task error moves in the wrong direction.</p>
<p>For example, reducing domain MMD in a vision representation does not by itself show that the classifier’s margin distribution, class-conditional overlap, or false-positive rate improved. It only shows that the chosen source and target distributions became closer in the chosen RKHS geometry. The same warning applies to representation monitoring. A shift score in embedding space can be a useful alarm, but it is not automatically an accuracy-drop estimate. To make it operational, one should check whether the score is aligned with the deployed model’s margin distribution, class-conditional errors, false-positive rate, or task-specific loss. Without that link, the score remains a diagnostic of representation geometry, not a statement about downstream risk.</p>
<p>The missing question is always</p>
<p><span class="math display">
P\{\widehat g(z)\ne y\}.
</span></p>
<p>Or, in asymmetric problems,</p>
<p><span class="math display">
P\{\widehat g(z)=2\mid z\in\pi_1\}.
</span></p>
<p>A discrepancy is not wrong because it differs from classification error. It becomes misleading only when it is interpreted as classification error without proving the link.</p>
<p>A useful workflow is</p>
<p><span class="math display">
\text{population model}
\rightarrow
\text{decision rule}
\rightarrow
\text{distribution of the decision statistic}
\rightarrow
\text{misclassification probability}.
</span></p>
<p>A weaker workflow is</p>
<p><span class="math display">
\text{population model}
\rightarrow
\text{distance between distributions}
\rightarrow
\text{informal claim about classification}.
</span></p>
<p>The second workflow is where the mistake enters.</p>
<h2 id="takeaway">Takeaway</h2>
<p>None of these distances is the villain. MMD, Wasserstein distance, Euclidean distance, and Mahalanobis distance are all useful when read as answers to the questions they actually ask.</p>
<p>The danger is the interpretation placed on them.</p>
<p>A distribution discrepancy answers a distribution question. A classifier error answers a decision question. They can agree when the geometry, model, and classifier are aligned. They can separate when the discrepancy listens to the wrong coordinate, the wrong scale, the wrong covariance, the wrong finite-sample object, the wrong marginal, or the wrong higher moments.</p>
<p>The diagnostic question is:</p>
<blockquote>
<p>Does this discrepancy control the error of the rule I will actually use?</p>
</blockquote>
<p>If yes, the discrepancy has operational meaning. If no, it is still useful as a geometric diagnostic, but it should not be reported as evidence of lower risk. A small discrepancy can be false comfort; a large discrepancy can be irrelevant alarm.</p>
<h2 id="references">References</h2>
<p>Bai, Z. D., and Saranadasa, H. “Effect of High Dimension: By an Example of a Two Sample Problem.” <em>Statistica Sinica</em> 6, 1996.</p>
<p>Saranadasa, H. “Asymptotic Expansion of the Misclassification Probabilities of D- and A-Criteria for Discrimination from Two High Dimensional Populations Using the Theory of Large Dimensional Random Matrices.” <em>Journal of Multivariate Analysis</em> 46(1), 1993.</p>
<p>Yao, J., Zheng, S., and Bai, Z. <em>Large Sample Covariance Matrices and High-Dimensional Data Analysis</em>. Cambridge University Press, 2015.</p>
<p>Gretton, A., Borgwardt, K. M., Rasch, M. J., Schölkopf, B., and Smola, A. “A Kernel Two-Sample Test.” <em>Journal of Machine Learning Research</em> 13, 2012.</p>
<p>Ben-David, S., Blitzer, J., Crammer, K., Kulesza, A., Pereira, F., and Vaughan, J. W. “A Theory of Learning from Different Domains.” <em>Machine Learning</em> 79, 2010.</p>
<p>Long, M., Cao, Y., Wang, J., and Jordan, M. I. “Learning Transferable Features with Deep Adaptation Networks.” <em>Proceedings of ICML</em>, 2015.</p>
<h2 id="suggested-citation">Suggested citation</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="va">@misc</span>{<span class="ot">miryusupov2026discrepancyrisk</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>       = {Miryusupov, Shohruh},</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>        = {Discrepancy Is Not Risk},</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>         = {2026},</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">howpublished</span> = {Research note},</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">url</span>          = {https://www.miryusupov.com/blog/posts/discrepancy_is_not_risk/}</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>


<footer id="site-footer" class="site-footer">
  <span class="site-disclaimer">
    Personal academic site. Views and notes are my own and do not represent my employer. Written independently, using public sources and personal resources.
  </span>
</footer>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const footer = document.getElementById("site-footer");
    if (footer) {
      document.body.appendChild(footer);
    }
  });
</script>

<script>
document.addEventListener("DOMContentLoaded", () => {
  const tocLinks = [...document.querySelectorAll("#TOC a[href^='#']")];
  const sections = tocLinks
    .map(link => document.querySelector(decodeURIComponent(link.getAttribute("href"))))
    .filter(Boolean);

  if (!tocLinks.length || !sections.length) return;

  const setActive = () => {
    let active = sections[0];

    for (const section of sections) {
      if (section.getBoundingClientRect().top <= 120) {
        active = section;
      }
    }

    tocLinks.forEach(link => {
      link.classList.toggle(
        "active",
        link.getAttribute("href") === "#" + CSS.escape(active.id)
      );
    });
  };

  setActive();
  window.addEventListener("scroll", setActive, { passive: true });
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
    tabsets.forEach(function(tabset) {
      const tabby = new Tabby('#' + tabset.id);
    });
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/www\.miryusupov\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'light-border',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>




</body></html>